name: C Project CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile project
      run: gcc 1_source_files/*.c -o mem

    - name: Run program
      run: ./mem